version: "3.9"

services:
  suivi_encaissement_web:
    image: dstdcie17/suivi_encaissement_web:1.0.3
    container_name: suivi_encaissement_web
    ports:
      - "2403:2403"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
