version: '3.8'

services:
  suivi_encaissement_web:
    image: dstdcie17/suivi_encaissement_web:latest
    container_name: suivi_encaissement_web
    ports:
      - '2403:2403'
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    # Uncomment and modify if you need to persist data
    # volumes:
    #   - ./data:/app/data